#!/bin/bash

# write version
TO=20191027

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# color code
RED='\033[0;31m'
NC='\033[0m'
YELLOW='\033[0;33m'

# change log
echo -e "\n${YELLOW}201920191010 to $TO update\n${NC}1. install bash-completion / command-not-found / dialog.\n2. fix aol boot time (add sleep 30)."

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    
    cat <<EOF > /etc/apt/sources.list
# debian stretch repo
deb http://ftp.kr.debian.org/debian/ stretch main contrib non-free
deb-src http://ftp.kr.debian.org/debian/ stretch main contrib non-free

# debian stretch-backports repo
deb http://ftp.kr.debian.org/debian stretch-backports main contrib non-free
deb-src http://ftp.kr.debian.org/debian stretch-backports main contrib non-free

# debian stretch-updates repo
deb http://ftp.kr.debian.org/debian stretch-updates main contrib non-free
deb-src http://ftp.kr.debian.org/debian stretch-updates main contrib non-free

EOF

    apt update && apt install bash-completion command-not-found dialog -y
    apt update
    update-command-not-found
    
    cat <<EOF > /system/etc/init.ghost.linux
#!/system/bin/sh
sleep 30
if [ -f /sdcard/aolrun ]; then
	if [[ ! -f /data/linux/dev/kmsg ]]; then
	        # internal linux init script
			ROOT=/data/linux
	        busybox sysctl -w net.ipv4.ip_forward=1
	        busybox rm -rf $ROOT/dev/*
	        busybox mount -t sysfs sysfs $ROOT/sys
	        busybox mount -t proc proc $ROOT/proc
	        busybox mount -o bind /dev $ROOT/dev
	        busybox mount -t devpts devpts $ROOT/dev/pts
	        busybox mkdir $ROOT/dev/shm
	        busybox mount -t tmpfs tmpfs $ROOT/dev/shm
	        busybox rm -rf $ROOT/run/*
	        busybox mount -t tmpfs tmpfs $ROOT/run
	        busybox mkdir $ROOT/run/lock
	        busybox mount -o bind /dev/socket $ROOT/dev/socket
	        mount -o bind,rshared /mnt $ROOT/mnt
	        busybox mount -o bind /system $ROOT/system
	        busybox mount -o bind /data $ROOT/data
	        busybox mkdir $ROOT/vendor
	        busybox mount -o bind /vendor $ROOT/vendor
			busybox mount -o bind /storage $ROOT/storage
			busybox chroot $ROOT /bin/su root -c "/etc/init.d/rc 3" > /dev/kmsg
		
			# kodi hostname patch
			LINUXHOSTNAME=`hostname`
			if [ "`grep $LINUXHOSTNAME /system/etc/hosts -c`" == "0" ]; then
				mount -o rw,remount /system
				sed -i "1s/.*/127.0.0.1       localhost/g" /system/etc/hosts
				sed -i "s/127.0.0.1       localhost/127.0.0.1       localhost $LINUXHOSTNAME/" /system/etc/hosts
				mount -o ro,remount /system
			fi
	fi
fi
EOF

    # info message
    echo -e "${YELLOW}[update] ${NC}update to $TO finished..."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
