#!/bin/bash

# write version
TO=20191221

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# color code
RED='\033[0;31m'
NC='\033[0m'
YELLOW='\033[0;33m'

# change log
echo -e "\n${YELLOW}20191103 to $TO update\n${NC}1. aolinit freezing fix."

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    
    cat <<'EOF' > /system/etc/init.ghost.linux
if [ -f /sdcard/aolrun ]; then
	if [[ ! -f /data/linux/dev/kmsg ]]; then
	        # internal linux init script
			ROOT=/data/linux
			
	        busybox sysctl -w net.ipv4.ip_forward=1

			# make /dev /proc /sys
	    busybox rm -rf $ROOT/dev/*
			busybox mount -t proc proc $ROOT/proc
	    busybox mount -t sysfs sys $ROOT/sys
	    busybox mount -o bind /dev $ROOT/dev
			busybox mount -o rw,nosuid,nodev,mode=1777 -t tmpfs tmpfs /dev/shm
			busybox mount -o bind /dev/pts $ROOT/dev/pts
			busybox ln -s /proc/self/fd/0 /dev/stdin
			busybox ln -s ln -s /proc/self/fd/1 /dev/stdout
			busybox ln -s /proc/self/fd/2 /dev/stderr
			
			# make /run
	    busybox rm -rf $ROOT/run/*
	    busybox mount -t tmpfs tmpfs $ROOT/run
	    busybox mkdir $ROOT/run/lock

			# android partitions bind
			mount -o bind,rshared /mnt $ROOT/mnt
	    busybox mount -o bind /system $ROOT/system
	    busybox mount -o bind /data $ROOT/data
	    busybox mkdir $ROOT/vendor
	    busybox mount -o bind /vendor $ROOT/vendor
			busybox mount -o bind /storage $ROOT/storage
			sleep 60
			
			# start sysv-init script
			busybox chroot $ROOT /bin/su root -c "/etc/init.d/rc 3" > /dev/null 2>&1
		
			# kodi hostname patch
			LINUXHOSTNAME=`hostname`
			if [ "`grep $LINUXHOSTNAME /system/etc/hosts -c`" == "0" ]; then
				mount -o rw,remount /system
				sed -i "1s/.*/127.0.0.1       localhost/g" /system/etc/hosts
				sed -i "s/127.0.0.1       localhost/127.0.0.1       localhost $LINUXHOSTNAME/" /system/etc/hosts
				mount -o ro,remount /system
			fi
	fi
fi
EOF

    apt update 

    # info message
    echo -e "${YELLOW}[update] ${NC}update to $TO finished..."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
